# Generated by Django 3.0.3 on 2020-03-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0003_auto_20200315_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sem1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=11)),
                ('date', models.DateField()),
                ('reminder', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sem2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=11)),
                ('date', models.DateField()),
                ('reminder', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sem3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=11)),
                ('date', models.DateField()),
                ('reminder', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sem4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=11)),
                ('date', models.DateField()),
                ('reminder', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sem5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=11)),
                ('date', models.DateField()),
                ('reminder', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sem6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=11)),
                ('date', models.DateField()),
                ('reminder', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sem7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=11)),
                ('date', models.DateField()),
                ('reminder', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sem8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=11)),
                ('date', models.DateField()),
                ('reminder', models.CharField(max_length=500)),
            ],
        ),
    ]
