# Generated by Django 3.0.3 on 2020-03-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0004_sem1_sem2_sem3_sem4_sem5_sem6_sem7_sem8'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=11)),
                ('date', models.DateField()),
                ('reminder', models.CharField(max_length=500)),
                ('sem', models.CharField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Sem1',
        ),
        migrations.DeleteModel(
            name='Sem2',
        ),
        migrations.DeleteModel(
            name='Sem3',
        ),
        migrations.DeleteModel(
            name='Sem4',
        ),
        migrations.DeleteModel(
            name='Sem5',
        ),
        migrations.DeleteModel(
            name='Sem6',
        ),
        migrations.DeleteModel(
            name='Sem7',
        ),
        migrations.DeleteModel(
            name='Sem8',
        ),
    ]
