# Generated by Django 3.0.3 on 2020-03-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0005_auto_20200328_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder_student',
            name='sem',
            field=models.CharField(max_length=9),
        ),
    ]
