# Generated by Django 3.0.3 on 2020-03-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0007_auto_20200328_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder_student',
            name='sem',
            field=models.CharField(max_length=8),
        ),
    ]
