# Generated by Django 3.0.5 on 2020-04-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0008_auto_20200328_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder_faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=11)),
                ('date', models.DateField()),
                ('reminder', models.CharField(max_length=500)),
            ],
        ),
    ]
