# Generated by Django 3.0.5 on 2020-04-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_auto_20200402_2243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadMetirial_CE',
        ),
    ]
