# Generated by Django 3.0.3 on 2020-03-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminloginapp', '0003_auto_20200226_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_ec',
            name='gender',
            field=models.CharField(default='', max_length=6),
        ),
    ]
