# Generated by Django 3.0.3 on 2020-03-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminloginapp', '0004_auto_20200302_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_ce',
            name='gender',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='student_ch',
            name='gender',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='student_cl',
            name='gender',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='student_ic',
            name='gender',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='student_it',
            name='gender',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='student_mh',
            name='gender',
            field=models.CharField(default='', max_length=6),
        ),
    ]
