# Generated by Django 3.0.3 on 2020-03-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminloginapp', '0005_auto_20200302_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty_ce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=20)),
                ('lname', models.CharField(default='', max_length=20)),
                ('gender', models.CharField(default='', max_length=6)),
                ('bdate', models.DateField()),
                ('branch', models.CharField(default='', max_length=4)),
                ('mno', models.CharField(default='', max_length=12)),
                ('userid', models.CharField(default='', max_length=11)),
                ('password', models.CharField(default='', max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_ch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=20)),
                ('lname', models.CharField(default='', max_length=20)),
                ('gender', models.CharField(default='', max_length=6)),
                ('bdate', models.DateField()),
                ('branch', models.CharField(default='', max_length=4)),
                ('mno', models.CharField(default='', max_length=12)),
                ('userid', models.CharField(default='', max_length=11)),
                ('password', models.CharField(default='', max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_cl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=20)),
                ('lname', models.CharField(default='', max_length=20)),
                ('gender', models.CharField(default='', max_length=6)),
                ('bdate', models.DateField()),
                ('branch', models.CharField(default='', max_length=4)),
                ('mno', models.CharField(default='', max_length=12)),
                ('userid', models.CharField(default='', max_length=11)),
                ('password', models.CharField(default='', max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_ec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=20)),
                ('lname', models.CharField(default='', max_length=20)),
                ('gender', models.CharField(default='', max_length=6)),
                ('bdate', models.DateField()),
                ('branch', models.CharField(default='', max_length=4)),
                ('mno', models.CharField(default='', max_length=12)),
                ('userid', models.CharField(default='', max_length=11)),
                ('password', models.CharField(default='', max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_ic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=20)),
                ('lname', models.CharField(default='', max_length=20)),
                ('gender', models.CharField(default='', max_length=6)),
                ('bdate', models.DateField()),
                ('branch', models.CharField(default='', max_length=4)),
                ('mno', models.CharField(default='', max_length=12)),
                ('userid', models.CharField(default='', max_length=11)),
                ('password', models.CharField(default='', max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_it',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=20)),
                ('lname', models.CharField(default='', max_length=20)),
                ('gender', models.CharField(default='', max_length=6)),
                ('bdate', models.DateField()),
                ('branch', models.CharField(default='', max_length=4)),
                ('mno', models.CharField(default='', max_length=12)),
                ('userid', models.CharField(default='', max_length=11)),
                ('password', models.CharField(default='', max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_mh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=20)),
                ('lname', models.CharField(default='', max_length=20)),
                ('gender', models.CharField(default='', max_length=6)),
                ('bdate', models.DateField()),
                ('branch', models.CharField(default='', max_length=4)),
                ('mno', models.CharField(default='', max_length=12)),
                ('userid', models.CharField(default='', max_length=11)),
                ('password', models.CharField(default='', max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
