# Generated by Django 3.0.3 on 2020-03-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminloginapp', '0006_faculty_ce_faculty_ch_faculty_cl_faculty_ec_faculty_ic_faculty_it_faculty_mh'),
    ]

    operations = [
        migrations.CreateModel(
            name='ce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField(max_length=1)),
                ('uptime', models.DateTimeField()),
                ('userid', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=150)),
            ],
        ),
    ]
