# Generated by Django 3.0.3 on 2020-03-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminloginapp', '0007_ce'),
    ]

    operations = [
        migrations.CreateModel(
            name='ch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField(max_length=1)),
                ('uptime', models.DateTimeField()),
                ('userid', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='cl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField(max_length=1)),
                ('uptime', models.DateTimeField()),
                ('userid', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField(max_length=1)),
                ('uptime', models.DateTimeField()),
                ('userid', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField(max_length=1)),
                ('uptime', models.DateTimeField()),
                ('userid', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='it',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField(max_length=1)),
                ('uptime', models.DateTimeField()),
                ('userid', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='mh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField(max_length=1)),
                ('uptime', models.DateTimeField()),
                ('userid', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=150)),
            ],
        ),
    ]
