# Generated by Django 3.0.3 on 2020-03-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminloginapp', '0011_auto_20200314_2204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ce',
        ),
        migrations.DeleteModel(
            name='ch',
        ),
        migrations.DeleteModel(
            name='cl',
        ),
        migrations.DeleteModel(
            name='ec',
        ),
        migrations.DeleteModel(
            name='ic',
        ),
        migrations.DeleteModel(
            name='it',
        ),
        migrations.DeleteModel(
            name='mh',
        ),
    ]
