# Generated by Django 3.0.3 on 2020-03-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminloginapp', '0015_auto_20200317_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_ce',
            name='regtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='faculty_ch',
            name='regtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='faculty_cl',
            name='regtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='faculty_ec',
            name='regtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='faculty_ic',
            name='regtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='faculty_it',
            name='regtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='faculty_mh',
            name='regtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='student_ce',
            name='regtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='student_ch',
            name='regtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='student_cl',
            name='regtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='student_ec',
            name='regtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='student_ic',
            name='regtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='student_it',
            name='regtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='student_mh',
            name='regtime',
            field=models.DateTimeField(),
        ),
    ]
