# Generated by Django 3.0.5 on 2020-04-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminloginapp', '0016_auto_20200317_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_ce',
            name='email_request',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='student_ch',
            name='email_request',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='student_cl',
            name='email_request',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='student_ec',
            name='email_request',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='student_ic',
            name='email_request',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='student_it',
            name='email_request',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='student_mh',
            name='email_request',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
